# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: installing hugo 
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.deb
          sudo dpkg -i hugo_0.80.0_Linux-64bit.deb
          rm hugo_0.80.0_Linux-64bit.deb
          hugo version
      - name: build public 
        run: |
          rm -rf public/
          hugo -D
      - name: push changes to remote
        run: |
          git config --global user.name "Starmedica-blog"
          git config --global user.email "starmedicalediting@gmail.com"
          
          git add .
          git commit -m "Update from Actions"
          git push
